### ISSUE TITLE
Disable extendability

### ISSUE THREAD

**Issue by eirnym** [taleinat/python-stdlib-sentinels#2]
Thank you for a nice and clean idea and a reference implementation to provide a standard way to define a sentinel. 

I'd like to ask to improve reference implementation with closing ability to define any properties or extending the object. 

With reference implementation I see usage of slots mechanism and making this class final. There's no reason to provide extendable implementation for sentinels as they are as a `None` just singletons.

**Comment by taleinat** [comment]
Thank you for the kind words and for the suggestion!

Note that I've recently added explicit support for sub-classing Sentinel.

Since there is no technical reason to disallow sub-classing and extending Sentinel, I'd rather not make such limitations. This is in keeping with the spirit of Python and the stdlib.

I'm also leaning against using slots. I don't expect there to be very many such objects created in normal circumstances, and I very much want to keep things as simple as possible. And with the recently added support for sub-classing, one could easily create a sub-class which uses slots if desired.

**Comment by eirnym** [comment]
Thanks for an explanation!
